# Polynomial Features

Paulo Cysne Rios Jr. | Novembro 2017

In [3]:
import numpy as np

In [6]:
import matplotlib.pyplot as plt

In [20]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [8]:
m = 100
X = 6 * np.random.rand(m, 1) - 3
y = 0.5 * X**2 + X + 2   

In [12]:
# Acrescentando noise
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)

In [13]:
plt.plot(X, y_predict, "r-")
plt.scatter(X, y, color = "blue", alpha = 0.6)
plt.show()

In [15]:
lpolyf_m = PolynomialFeatures(degree=2, include_bias=False)

In [16]:
X_poly = lpolyf_m.fit_transform(X)

In [17]:
X[0]

array([-2.67231315])

In [18]:
X_poly[0]

array([-2.67231315,  7.14125755])

In [21]:
lg_m = LinearRegression()

In [22]:
lg_m.fit(X_poly, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [24]:
lg_m.intercept_, lg_m.coef_

(array([ 2.25489488]), array([[ 1.02756995,  0.47746374]]))

In [27]:
y_predict = lg_m.predict(X_poly)

In [31]:
plt.scatter(X, y_predict, color = "red", alpha = 0.6)
plt.scatter(X, y, color = "blue", alpha = 0.6)
plt.show()